version: "3.3"

volumes:
  letsencrypt:
  db:
  app:

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #-"--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=alarm@www.projet-tut-s2-12.ml"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
 
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
      - "389:389"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`www.projet-tut-s2-12.ml`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
  db:
    image: postgres
    container_name: db
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user

  app:
    image: nextcloud
    container_name: app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`nextcloud.projet-tut-s2-12.ml`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    volumes:
      - "app:/var/www/html"
    environment:
      - POSTGRES_HOST=$NEXTCLOUD_POSTGRES_HOST
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.projet-tut-s2-12.ml

    depends_on:
      - db

    secrets:
      - nextcloud_admin_password      
      - nextcloud_admin_user
      - postgres_db
      - postgres_password
      - postgres_user     


secrets:
  nextcloud_admin_password:
    file: ../secret/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ../secret/nextcloud_admin_user.txt
  postgres_db:
    file: ../secret/postgres_db.txt 
  postgres_password:
    file: ../secret/postgres_password.txt
  postgres_user:
    file: ../secret/postgres_user.txt  
