version: "3.3"

volumes:
  letsencrypt:
  db:
  app:

services:

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      #-"--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      #- "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=alarm@www.projet-tut-s2-12.ml"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
 
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "letsencrypt:/letsencrypt"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`www.projet-tut-s2-12.ml`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
  db:
    image: postgres
    container_name: db
    volumes:
      - "db:/var/lib/postgresql/data"
    environment:
      #- POSTGRES_ROOT_PASSWORD=$NEXTCLOUD_POSTGRES_ROOT_PASSWORD  # Mot de passe de l'utilisateur root de mariadb
      - POSTGRES_DB=$NEXTCLOUD_POSTGRES_DATABASE  # Nom de la base de donnees creer l'itialisation du conteneur
      - POSTGRES_USER=$NEXTCLOUD_POSTGRES_USER  # Nom de l'utilisateur de la base de donn      es cr            e
      - POSTGRES_PASSWORD=$NEXTCLOUD_POSTGRES_PASSWORD  # Mot de passe de l'utilisateur cr

  app:
    image: nextcloud
    container_name: app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`nextcloud.projet-tut-s2-12.ml`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
    volumes:
      - "app:/var/www/html"
    environment:
      - POSTGRES_HOST=$NEXTCLOUD_POSTGRES_HOST  # Nom du conteneur de la base de donnees
      - POSTGRES_DB=$NEXTCLOUD_POSTGRES_DATABASE  # Nom de la base de donnees
      - POSTGRES_USER=$NEXTCLOUD_POSTGRES_USER  # Nom de l'utilisateur de la base de donnees
      - POSTGRES_PASSWORD=$NEXTCLOUD_POSTGRES_PASSWORD  # Mot de passe de l'utilisateur de la base de donnees
      - NEXTCLOUD_ADMIN_USER=$NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD=$NEXTCLOUD_ADMIN_PASSWORD
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.projet-tut-s2-12.ml

    depends_on:
      - db
